window.DREAM_DATA = {
  profile: {
    username: "@your_account",
    brand: "dream.private",
    displayName: "你的顯示名稱",
    avatarImage: "",
    lines: [
      "第一行：簡短介紹你是誰，例如夢女｜多作品夢向｜二創收藏。",
      "第二行：可以寫公開程度、交流取向或頁面用途。",
      "第三行：可以寫所在地、年齡區間、注意事項；不想公開就刪掉。",
    ],
    linkText: "› pinned post｜關於我 & 交流守則",
    following: "0",
    footer: "© your name — dream profile",
  },
  about: {
    title: "關於我",
    paragraphs: [
      "在這裡寫自我介紹。可以說明這個帳號會放夢向、日常、委託紀錄、設定整理或其他內容。",
      "如果不同作品有不同交流規則，可以提醒訪客往下看坑單或夢角檔案。",
    ],
  },
  rules: {
    title: "交流守則",
    items: [
      "這裡寫你的交流規則，例如同擔、同嫁、夢向避雷、轉載規則。",
      "不需要的規則可以刪掉；需要更多就直接新增一行。",
      "建議用清楚但不攻擊的語氣，讓訪客知道怎麼互動最舒服。",
    ],
  },
  message: {
    title: "最後的小提醒",
    text: "這裡可以放補充說明、感謝閱讀、或提醒訪客到 Social Links 選擇聯絡方式。模板詳細說明請看 GitHub 詳情頁。",
  },
  pitList: [
    {
      title: "目前主坑",
      items: [
        {
          work: "作品名",
          mainOshi: "主推",
          subOshi: "副推或箱推",
          cp: "吃的 CP 或組合",
          note: "備註，例如有夢角、劇透注意、主坑。",
        },
      ],
    },
    {
      title: "單純坑 / 沒有夢角",
      items: [
        {
          work: "作品名",
          mainOshi: "",
          subOshi: "",
          cp: "",
          note: "如果只想記錄坑單，可以只填作品名和備註。",
        },
      ],
    },
  ],
  socialLinks: [
    {
      label: "平台名稱",
      handle: "@your_id",
      url: "https://example.com/",
      note: "這裡寫用途，例如主要聯絡、匿名箱、委託紀錄。",
      icon: "link",
      iconColor: "#8cc9ff",
      iconImage: "",
      iconImageMode: "color",
    },
    {
      label: "另一個連結",
      handle: "顯示文字",
      url: "https://example.com/",
      note: "可以在後台新增、刪除、排序社群連結。",
      icon: "mail",
      iconColor: "#bba7ff",
      iconImage: "",
      iconImageMode: "color",
    },
  ],
  posts: [
    {
      id: "01",
      work: "作品名",
      character: "夢角名",
      relation: "關係定位，例如戀人向、親情向、友情向、知己向",
      dreamer: "夢主名",
      status: "公開狀態，例如主夢、低浮上、草稿",
      boundaries: ["同擔：請填寫", "同嫁：請填寫", "雷點：請填寫"],
      tags: ["#作品名", "#夢角名"],
      note: "這裡寫補充設定、公開程度、劇透提醒、委託圖或口嗨規則。",
      color: "#8cc9ff",
      icon: "star",
      iconImage: "",
      iconImageMode: "color",
    },
    {
      id: "02",
      work: "第二個作品名",
      character: "第二位夢角名",
      relation: "關係定位",
      dreamer: "夢主名",
      status: "草稿",
      boundaries: ["同擔：請填寫", "同嫁：請填寫", "雷點：請填寫"],
      tags: ["#第二個作品名", "#夢角名"],
      note: "複製這張卡可以新增更多夢角；也可以直接到後台按新增夢角。",
      color: "#d6a03b",
      icon: "heart",
      iconImage: "",
      iconImageMode: "color",
    },
  ],
};
