window.DREAM_DATA = {
  profile: {
    username: "@dream.private",
    brand: "dream.private",
    displayName: "夢の記錄者",
    lines: [
      "夢女｜多作品夢向｜二創收藏",
      "在夢裡與他們相遇，在這裡好好記錄。",
      "角色情感依作品、夢向狀態與交流距離調整。",
      "Taiwan / 成人 / 日常與夢的界線分明",
    ],
    linkText: "› pinned post｜關於我 & 交流守則",
    following: "0",
    footer: "© dream.private — 夢女檔案館",
  },
  about: {
    title: "關於我",
    paragraphs: [
      "這裡是夢向與日常分流的私人檔案帳。內容以自我滿足、設定整理、委託紀錄、碎碎念為主。",
      "不同作品的同擔同嫁規則可能不同，請以各篇置頂檔案為準。",
    ],
  },
  rules: {
    title: "交流守則",
    items: [
      "未經同意請勿搬運、轉載或二次加工。",
      "夢向內容多為個人主觀創作，角色歸於原作。",
      "不適合的交流會自行避開，彼此舒服最重要。",
    ],
  },
  message: {
    title: "最後的小提醒",
    text: "這個頁面可以當成 Carrd 排版稿，也可以直接免費部署成網站。後台可以修改資料並匯出 data.js。",
  },
  pitList: [
    {
      title: "目前主坑",
      items: ["黎明的誓約", "月蝕之夜", "王座之側"],
    },
    {
      title: "副坑 / 低浮上",
      items: ["深海的呼喚", "綠蔭下的羅曼史", "星屑協奏曲"],
    },
    {
      title: "暫停 / 草稿",
      items: ["時光停滯之處", "未完的詩篇"],
    },
  ],
  socialLinks: [
    {
      label: "X / Twitter",
      handle: "@your_id",
      url: "https://x.com/",
      note: "日常、口嗨、夢向碎念",
      icon: "x",
    },
    {
      label: "Plurk",
      handle: "your_plurk",
      url: "https://www.plurk.com/",
      note: "長串紀錄與互動",
      icon: "plurk",
    },
    {
      label: "Wavebox",
      handle: "匿名留言",
      url: "https://wavebox.me/",
      note: "留言、感想、投遞都可以",
      icon: "wavebox",
    },
    {
      label: "Instagram",
      handle: "@your_ig",
      url: "https://www.instagram.com/",
      note: "圖像整理與限動存放",
      icon: "instagram",
    },
  ],
  posts: [
    {
      id: "01",
      work: "黎明的誓約",
      character: "艾爾文",
      relation: "夢女設定 / 戀人向",
      dreamer: "夢主名",
      status: "主夢",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#黎明的誓約", "#艾爾文", "#主夢"],
      note: "主關於他的紀錄與碎碎念。內容含原作劇透，慎入。",
      color: "#d46a5d",
      icon: "rose",
    },
    {
      id: "02",
      work: "深海的呼喚",
      character: "雷克",
      relation: "夢女設定 / 戀人向",
      dreamer: "夢主名",
      status: "副夢",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#深海的呼喚", "#雷克", "#副夢"],
      note: "雷點自避，感謝理解。偶爾更新。",
      color: "#68a8db",
      icon: "anchor",
    },
    {
      id: "03",
      work: "綠蔭下的羅曼史",
      character: "雷恩",
      relation: "夢女設定 / 清純竹馬向",
      dreamer: "夢主名",
      status: "慢更",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#綠蔭下的羅曼史", "#雷恩"],
      note: "日常向偏多，慢慢更新。歡迎留言聊天。",
      color: "#90aa69",
      icon: "leaf",
    },
    {
      id: "04",
      work: "月蝕之夜",
      character: "夜斗",
      relation: "夢女設定 / 救贖向",
      dreamer: "夢主名",
      status: "主夢",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#月蝕之夜", "#夜斗", "#夜色"],
      note: "暗黑元素偏多，偶爾流作品。請詳細閱讀。",
      color: "#9b78e8",
      icon: "butterfly",
    },
    {
      id: "05",
      work: "時光停滯之處",
      character: "基爾伯特",
      relation: "夢女設定 / 師徒向",
      dreamer: "夢主名",
      status: "低浮上",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#時光停滯之處", "#基爾伯特"],
      note: "時間線混亂注意。有大量回憶向內容。",
      color: "#d6a03b",
      icon: "clock",
    },
    {
      id: "06",
      work: "星屑協奏曲",
      character: "卡諾",
      relation: "夢女設定 / 偶像向",
      dreamer: "夢主名",
      status: "副夢",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#星屑協奏曲", "#卡諾"],
      note: "舞台與夢境交織的紀錄。請理性追歡，開心聊天。",
      color: "#65c7ce",
      icon: "star",
    },
    {
      id: "07",
      work: "王座之側",
      character: "路德維希",
      relation: "夢女設定 / 權力平衡向",
      dreamer: "夢主名",
      status: "主夢",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#王座之側", "#路德維希"],
      note: "宮廷暗線向，劇透注意。尊重彼此很重要。",
      color: "#d95778",
      icon: "crown",
    },
    {
      id: "08",
      work: "未完的詩篇",
      character: "賽西爾",
      relation: "夢女設定 / 知己向",
      dreamer: "夢主名",
      status: "草稿",
      boundaries: ["不接受 3P、NP、R18G", "不拆逆 / 不吃夢刪除", "可友善交流，尊重即可"],
      tags: ["#未完的詩篇", "#賽西爾"],
      note: "文字創作為主，靈感紀錄。不定期更新。",
      color: "#b9b7b4",
      icon: "feather",
    },
  ],
};
